# Generated by Django 3.0.7 on 2022-01-19 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_salonaccount_frontendappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierName', models.CharField(max_length=50)),
                ('supplierTel', models.CharField(max_length=15)),
                ('supplierEmail', models.CharField(blank=True, max_length=100, null=True)),
                ('supplierAddress1', models.CharField(blank=True, max_length=100, null=True)),
                ('supplierTown', models.CharField(blank=True, max_length=100, null=True)),
                ('supplierCounty', models.CharField(blank=True, max_length=100, null=True)),
                ('supplierPostCode', models.CharField(blank=True, max_length=10, null=True)),
                ('supplierCountry', models.CharField(blank=True, max_length=100, null=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount')),
            ],
            options={
                'unique_together': {('salon', 'supplierTel')},
            },
        ),
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=25)),
                ('shelf', models.CharField(max_length=4)),
                ('box', models.CharField(max_length=4)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount')),
            ],
            options={
                'unique_together': {('salon', 'location', 'shelf', 'box')},
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=150, unique=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount')),
            ],
            options={
                'verbose_name_plural': 'Product categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=250)),
                ('productCode', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('stockQuantity', models.PositiveSmallIntegerField()),
                ('orderTime', models.DateField(blank=True, null=True)),
                ('sellPrice', models.FloatField(blank=True, null=True)),
                ('buyPrice', models.FloatField(blank=True, null=True)),
                ('stockInTime', models.DateField(blank=True, null=True)),
                ('decription', models.TextField(blank=True, null=True)),
                ('quanlity', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('lowStock', models.PositiveSmallIntegerField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.ProductCategory')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount')),
                ('storeLocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.StoreLocation')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Supplier')),
            ],
            options={
                'unique_together': {('salon', 'productName', 'productCode', 'supplier')},
            },
        ),
    ]
