# Generated by Django 3.0.7 on 2021-02-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonaccount',
            name='frontEndAppointment',
            field=models.BooleanField(default=False),
        ),
    ]
