# Generated by Django 3.0.7 on 2021-02-18 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(blank=True, null=True)),
                ('special', models.BooleanField(default=False)),
                ('notice', models.TextField(blank=True)),
                ('cancelID', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvailableChairTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ped_availables', models.TextField(blank=True, null=True)),
                ('ped_maxLength', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AvailableTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('availables', models.TextField(null=True)),
                ('maxLength', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'ordering': ['date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CallerID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ClosedDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('tel', models.CharField(blank=True, max_length=15, null=True)),
                ('address_1', models.CharField(blank=True, max_length=50, null=True)),
                ('address_2', models.CharField(blank=True, max_length=50, null=True)),
                ('town', models.CharField(blank=True, max_length=50, null=True)),
                ('postCode', models.CharField(blank=True, max_length=10, null=True)),
                ('notice', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraServiceBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('length', models.PositiveSmallIntegerField()),
                ('frontEnd', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenaralOpenTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openTime', models.TimeField()),
                ('closeTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OpenTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openTime', models.TimeField(blank=True, null=True)),
                ('closeTime', models.TimeField(blank=True, null=True)),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Moday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
            ],
        ),
        migrations.CreateModel(
            name='PedicureChairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QueueSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=159)),
                ('destination', models.CharField(max_length=13)),
                ('createTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalonStylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('length', models.PositiveSmallIntegerField()),
                ('pedicure_chair_length', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOpenTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('openTime', models.TimeField()),
                ('closeTime', models.TimeField()),
            ],
            options={
                'verbose_name': 'Special OpenTime',
                'verbose_name_plural': 'Special OpenTimes',
            },
        ),
        migrations.CreateModel(
            name='StoreLocker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxNumber', models.PositiveSmallIntegerField()),
                ('lastUsed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StylistExtraServiceLength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StylistServiceLength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TemplateAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appoinmentID', models.CharField(max_length=25)),
                ('appoinmentOTP', models.CharField(max_length=4)),
                ('appoinmentFName', models.CharField(max_length=25)),
                ('appoinmentLName', models.CharField(max_length=25)),
                ('appoinmentMobile', models.CharField(max_length=12)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('otpResend', models.DateTimeField(blank=True, null=True)),
                ('notice', models.CharField(blank=True, max_length=250, null=True)),
                ('waitFrom', models.DateTimeField(null=True)),
                ('waitTo', models.DateTimeField(null=True)),
                ('updatedTime', models.DateTimeField(auto_now=True)),
                ('notified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyCloseDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Moday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
            ],
        ),
        migrations.CreateModel(
            name='TempAppointment',
            fields=[
                ('appointment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customers.Appointment')),
            ],
            bases=('customers.appointment',),
        ),
    ]
