# Generated by Django 3.0.7 on 2021-02-18 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklycloseday',
            name='salonAcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount'),
        ),
        migrations.AddField(
            model_name='templateappointment',
            name='appoinmentEXtra',
            field=models.ManyToManyField(blank=True, to='customers.ExtraServiceBlock'),
        ),
        migrations.AddField(
            model_name='templateappointment',
            name='appoinmentService',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.ServiceBlock'),
        ),
        migrations.AddField(
            model_name='templateappointment',
            name='salonAcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount'),
        ),
        migrations.AddField(
            model_name='stylistservicelength',
            name='salonAcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount'),
        ),
        migrations.AddField(
            model_name='stylistservicelength',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.ServiceBlock'),
        ),
        migrations.AddField(
            model_name='stylistservicelength',
            name='stylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.SalonStylist'),
        ),
        migrations.AddField(
            model_name='stylistextraservicelength',
            name='extrsService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.ExtraServiceBlock'),
        ),
        migrations.AddField(
            model_name='stylistextraservicelength',
            name='salonAcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount'),
        ),
        migrations.AddField(
            model_name='stylistextraservicelength',
            name='stylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.SalonStylist'),
        ),
        migrations.AddField(
            model_name='storelocker',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customer'),
        ),
        migrations.AddField(
            model_name='storelocker',
            name='salonAcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount'),
        ),
        migrations.AddField(
            model_name='specialopentime',
            name='salonAcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount'),
        ),
        migrations.AddField(
            model_name='serviceblock',
            name='pedChair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.PedicureChairs'),
        ),
        migrations.AddField(
            model_name='serviceblock',
            name='salonAcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount'),
        ),
        migrations.AddField(
            model_name='salonstylist',
            name='salonAcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount'),
        ),
        migrations.AddField(
            model_name='pedicurechairs',
            name='salonAcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount'),
        ),
        migrations.AddField(
            model_name='opentimes',
            name='salonAcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount'),
        ),
        migrations.AddField(
            model_name='genaralopentime',
            name='salonAcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount'),
        ),
        migrations.AddField(
            model_name='extraserviceblock',
            name='salonAcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount'),
        ),
        migrations.AddField(
            model_name='customer',
            name='salonAcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount'),
        ),
        migrations.AddField(
            model_name='closedday',
            name='salonAcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount'),
        ),
        migrations.AddField(
            model_name='availabletimes',
            name='salonAcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount'),
        ),
        migrations.AddField(
            model_name='availabletimes',
            name='stylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.SalonStylist'),
        ),
        migrations.AddField(
            model_name='availablechairtimes',
            name='pedChair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.PedicureChairs'),
        ),
        migrations.AddField(
            model_name='availablechairtimes',
            name='salonAcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount'),
        ),
        migrations.AddField(
            model_name='appointmentstatus',
            name='salonAcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='extras',
            field=models.ManyToManyField(blank=True, to='customers.ExtraServiceBlock'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pedChair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.PedicureChairs'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='salonAcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.ServiceBlock'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.AppointmentStatus'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='stylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.SalonStylist'),
        ),
        migrations.AlterUniqueTogether(
            name='storelocker',
            unique_together={('salonAcc', 'boxNumber')},
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('salonAcc', 'mobile', 'firstName', 'lastName')},
        ),
        migrations.AlterUniqueTogether(
            name='availabletimes',
            unique_together={('salonAcc', 'stylist', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='availablechairtimes',
            unique_together={('salonAcc', 'pedChair', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('customer', 'dateTime', 'service', 'salonAcc', 'stylist')},
        ),
    ]
