# Generated by Django 3.0.7 on 2021-03-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210218_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraserviceblock',
            name='length',
            field=models.SmallIntegerField(),
        ),
    ]
