# Generated by Django 3.0.7 on 2021-04-26 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_salonaccount_frontendappointment'),
        ('customers', '0003_auto_20210319_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceblock',
            name='pedChair',
        ),
        migrations.CreateModel(
            name='NotTurnedUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                ('salonAcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.ServiceBlock')),
            ],
            options={
                'verbose_name': 'Not tunred up',
                'verbose_name_plural': 'Not tunred ups',
            },
        ),
    ]
