# Generated by Django 3.0.7 on 2021-04-28 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_salonaccount_frontendappointment'),
        ('customers', '0004_auto_20210426_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuesms',
            name='salonAcc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount'),
        ),
    ]
