# Generated by Django 3.0.7 on 2022-04-02 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_salonaccount_frontendappointment'),
        ('customers', '0005_queuesms_salonacc'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('salonAcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount')),
            ],
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='chair',
            new_name='chair',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pendding'), (1, 'Processing'), (2, 'Done'), (3, 'Cancelled'), (4, 'Not Turned Up')], default=0),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=50)),
                ('salonAcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount')),
            ],
        ),
        migrations.CreateModel(
            name='SalonEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('salonAcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('verify_id', models.CharField(max_length=15, unique=True)),
                ('verify_code', models.CharField(max_length=6)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=32)),
                ('expired', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(max_length=250)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxNumber', models.PositiveSmallIntegerField()),
                ('lastUsed', models.DateTimeField(blank=True, null=True)),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='serviceblock',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Service'),
        ),
        migrations.CreateModel(
            name='PedChairAvailablesCache',
            fields=[
                ('timescache_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customers.TimesCache')),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.PedicureChairs')),
            ],
            bases=('customers.timescache',),
        ),
        migrations.CreateModel(
            name='AvailableTimesCache',
            fields=[
                ('timescache_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customers.TimesCache')),
                ('chair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.PedicureChairs')),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.SalonStylist')),
            ],
            bases=('customers.timescache',),
        ),
    ]
