# Generated by Django 3.0.7 on 2021-12-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_queuesms_salonacc'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='session',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
