# Generated by Django 3.0.7 on 2022-01-17 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_salonaccount_frontendappointment'),
        ('customers', '0006_customer_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('salonAcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount')),
            ],
        ),
       


        migrations.CreateModel(
            name='SalonEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('salonAcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=32)),
                ('expired', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='PedChairAvailablesCache',
            fields=[
                ('timescache_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customers.TimesCache')),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.PedicureChairs')),
            ],
            bases=('customers.timescache',),
        ),
        migrations.CreateModel(
            name='AvailableTimesCache',
            fields=[
                ('timescache_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customers.TimesCache')),
                ('chair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.PedicureChairs')),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.SalonStylist')),
            ],
            bases=('customers.timescache',),
        ),
    ]
