# Generated by Django 3.0.7 on 2022-01-19 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20220117_1303'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='appointment',
        #     name='pedChair',
        # ),
        # migrations.RemoveField(
        #     model_name='customer',
        #     name='session',
        # ),
        # migrations.AddField(
        #     model_name='appointment',
        #     name='chair',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.PedicureChairs'),
        # ),
        # migrations.AlterField(
        #     model_name='appointment',
        #     name='status',
        #     field=models.PositiveSmallIntegerField(choices=[(0, 'Pendding'), (1, 'Processing'), (2, 'Done'), (3, 'Cancelled'), (4, 'Not Turned Up')], default=0),
        # ),
        migrations.CreateModel(
            name='CustomerVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('verify_id', models.CharField(max_length=15, unique=True)),
                ('verify_code', models.CharField(max_length=6)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(max_length=250)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxNumber', models.PositiveSmallIntegerField()),
                ('lastUsed', models.DateTimeField(blank=True, null=True)),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customer')),
            ],
        ),
    ]
