# Generated by Django 3.0.7 on 2022-03-11 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_salonaccount_frontendappointment'),
        ('customers', '0008_auto_20220119_1610'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='appointment',
        #     old_name='pedChair',
        #     new_name='chair',
        # ),
        # migrations.RemoveField(
        #     model_name='customer',
        #     name='session',
        # ),
        # migrations.AlterField(
        #     model_name='appointment',
        #     name='status',
        #     field=models.PositiveSmallIntegerField(choices=[(0, 'Pendding'), (1, 'Processing'), (2, 'Done'), (3, 'Cancelled'), (4, 'Not Turned Up')], default=0),
        # ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=50)),
                ('salonAcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SalonAccount')),
            ],
        ),
        migrations.AddField(
            model_name='serviceblock',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Service'),
        ),
    ]
