# Generated by Django 3.0.7 on 2022-02-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcetionLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(blank=True, max_length=250, null=True)),
                ('dateTime', models.DateTimeField()),
                ('exception', models.TextField()),
                ('error_code', models.CharField(max_length=20)),
            ],
        ),
    ]
