# Generated by Django 3.0.7 on 2022-04-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excetionlogs',
            name='error_code',
            field=models.CharField(max_length=10),
        ),
    ]
