# Generated by Django 3.0.7 on 2022-01-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excetionlogs',
            name='error_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
