# Generated by Django 3.0.7 on 2022-03-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_excetionlogs_error_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excetionlogs',
            name='error_code',
            field=models.CharField(max_length=10),
        ),
    ]
